/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import model.User;
import service.DatabaseConnection;

public class BUATLAPORANTINDAKLANJUT extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(BUATLAPORANTINDAKLANJUT.class.getName());

    private User currentUser;
    private Connection conn;
    private int selectedLaporanId = -1;

    public BUATLAPORANTINDAKLANJUT(User user) {
        this.currentUser = user;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
        loadLaporanTable();
        isiComboStatus();
    }

    public BUATLAPORANTINDAKLANJUT() {
        this.conn = DatabaseConnection.getConnection();
        initComponents();
        loadLaporanTable();
        isiComboStatus();
    }

    // === ISI COMBO STATUS ===
    private void isiComboStatus() {
        comboStatusTindak.removeAllItems();
        comboStatusTindak.addItem("Diproses");
        comboStatusTindak.addItem("Selesai");
        comboStatusTindak.addItem("Dibatalkan");
    }

    // === LOAD DATA LAPORAN KE TABEL ===
    private void loadLaporanTable() {
        try {
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("""
                SELECT id_laporan, jenis_laporan, deskripsi, status_laporan
                FROM laporan
                ORDER BY id_laporan DESC
            """);

            // Buat model sederhana tanpa DefaultTableModel
            javax.swing.table.DefaultTableModel tbl = new javax.swing.table.DefaultTableModel(
                new Object[]{"ID Laporan", "Jenis", "Deskripsi", "Status"}, 0
            );

            while (rs.next()) {
                Object[] data = {
                    rs.getInt("id_laporan"),
                    rs.getString("jenis_laporan"),
                    rs.getString("deskripsi"),
                    rs.getString("status_laporan")
                };
                tbl.addRow(data);
            }

            jTable1.setModel(tbl);

            // Klik baris untuk pilih laporan
            jTable1.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent e) {
                    int row = jTable1.getSelectedRow();
                    if (row >= 0) {
                        selectedLaporanId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());
                        JOptionPane.showMessageDialog(null,
                            "Laporan terpilih: ID " + selectedLaporanId,
                            "Info", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
            });

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat laporan: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Error load data laporan", e);
        }
    }
    
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboStatusTindak = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNominal = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboStatusTindak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboStatusTindak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusTindakActionPerformed(evt);
            }
        });
        getContentPane().add(comboStatusTindak, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 390, 530, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 450));
        getContentPane().add(txtNominal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 570, 50));
        getContentPane().add(txtHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 560, 50));

        next.setBackground(new java.awt.Color(0, 51, 153));
        next.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 180, 60));

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CAPSTONE.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
         if (selectedLaporanId == -1) {
            JOptionPane.showMessageDialog(this, "⚠️ Pilih laporan terlebih dahulu dari tabel!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String hasil = txtHasil.getText().trim();
        String nominalStr = txtNominal.getText().trim();
        String statusTindak = comboStatusTindak.getSelectedItem().toString();

        if (hasil.isEmpty() || nominalStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double nominal = Double.parseDouble(nominalStr);
            String sqlInsert = """
                INSERT INTO tindak_lanjut (id_laporan, tanggal_tindak, hasil_tindak, nominal_denda, status_tindakan)
                VALUES (?, CURDATE(), ?, ?, ?)
            """;

            PreparedStatement ps = conn.prepareStatement(sqlInsert);
            ps.setInt(1, selectedLaporanId);
            ps.setString(2, hasil);
            ps.setDouble(3, nominal);
            ps.setString(4, statusTindak);
            ps.executeUpdate();

            if (statusTindak.equalsIgnoreCase("Selesai")) {
                PreparedStatement ps2 = conn.prepareStatement(
                    "UPDATE laporan SET status_laporan = 'Selesai' WHERE id_laporan = ?");
                ps2.setInt(1, selectedLaporanId);
                ps2.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "✅ Tindak lanjut berhasil disimpan!");
            loadLaporanTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nominal denda harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal menyimpan tindak lanjut", e);
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    
        
        
        
    
    
    
        
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Menu_Admin(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void comboStatusTindakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusTindakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusTindakActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BUATLAPORANTINDAKLANJUT().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> comboStatusTindak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton next;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables
}
