/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import model.User;
import service.DatabaseConnection;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.time.LocalDate;
import java.io.FileInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
/**
 *
 * @author asus GK
 */

public class BuatLaporanPencemaranLaut_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(BuatLaporanPencemaranLaut_1.class.getName());

    private User currentUser;
    private int lokasiId;
    private Connection conn;
    private File selectedFile;

    // Konstruktor baru menerima user dan lokasiId
    public BuatLaporanPencemaranLaut_1(User user, int lokasiId) {
        this.currentUser = user;
        this.lokasiId = lokasiId;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
  
        conn = DatabaseConnection.getConnection();
    }

    public BuatLaporanPencemaranLaut_1() {
        this.conn = DatabaseConnection.getConnection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        uploadfoto = new javax.swing.JButton();
        Login4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        Login3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uploadfoto.setText("upload foto");
        uploadfoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadfotoActionPerformed(evt);
            }
        });
        getContentPane().add(uploadfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        Login4.setBackground(new java.awt.Color(0, 51, 153));
        Login4.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Login4.setForeground(new java.awt.Color(255, 255, 255));
        Login4.setText("Back");
        Login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login4ActionPerformed(evt);
            }
        });
        getContentPane().add(Login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 290, 90));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 560, 50));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 470, 30));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 550, 50));

        jCheckBox1.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Sedang");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 110, 30));

        jCheckBox4.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Berat");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 100, 30));

        jCheckBox5.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Ringan");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 100, 30));

        Login3.setBackground(new java.awt.Color(0, 51, 153));
        Login3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Send");
        Login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login3ActionPerformed(evt);
            }
        });
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 290, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pencemaranlaut_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login3ActionPerformed
        // TODO add your handling code here:
        String deskripsi = jTextField4.getText().trim();
        String jenisLimbah = jTextField5.getText().trim();
        String fotoPath = jTextField6.getText().trim();
        String tingkat = null;

        if (jCheckBox5.isSelected()) tingkat = "Ringan";
        else if (jCheckBox1.isSelected()) tingkat = "Sedang";
        else if (jCheckBox4.isSelected()) tingkat = "Berat";

        // Validasi dasar
        if (deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Deskripsi tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (lokasiId <= 0) {
            JOptionPane.showMessageDialog(this, "Data lokasi tidak valid. Silakan buat lokasi terlebih dahulu!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (tingkat == null) {
            JOptionPane.showMessageDialog(this, "Pilih tingkat pencemaran terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO laporan (id_pelapor, id_lokasi, tanggal_lapor, deskripsi, foto_bukti, status_laporan, jenis_laporan) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = conn.prepareStatement(sql);
             FileInputStream fis = (fotoPath.isEmpty()) ? null : new FileInputStream(new File(fotoPath))) {

            ps.setInt(1, currentUser.getIdUser());
            ps.setInt(2, lokasiId);
            ps.setDate(3, Date.valueOf(LocalDate.now()));
            ps.setString(4, deskripsi);

            if (fis != null) {
                ps.setBinaryStream(5, fis, (int) new File(fotoPath).length());
            } else {
                ps.setNull(5, Types.BLOB);
            }

            ps.setString(6, "Menunggu");
            ps.setString(7, "Pencemaran Laut");

            int inserted = ps.executeUpdate();

            if (inserted > 0) {
                JOptionPane.showMessageDialog(this, "✅ Laporan berhasil dikirim!");
                new Menu_Masyarakat(currentUser).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Gagal mengirim laporan.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan SQL: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "SQL Error", e);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan saat membaca file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "File IO Error", e);
        }
    


    
    
    }//GEN-LAST:event_Login3ActionPerformed

    private void Login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login4ActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void uploadfotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadfotoActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Pilih Foto Bukti Pencemaran Laut");
    fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    int result = fileChooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = fileChooser.getSelectedFile();

        // Validasi ekstensi file gambar
        String fileName = selectedFile.getName().toLowerCase();
        if (!(fileName.endsWith(".jpg") || fileName.endsWith(".jpeg") || 
              fileName.endsWith(".png") || fileName.endsWith(".gif"))) {
            JOptionPane.showMessageDialog(this, "File harus berupa gambar (jpg, jpeg, png, gif)!",
                "Format Tidak Didukung", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi ukuran file
        long fileSizeInBytes = selectedFile.length();
        long maxSizeInBytes = 2 * 1024 * 1024; // Maksimal 2 MB
        if (fileSizeInBytes > maxSizeInBytes) {
            JOptionPane.showMessageDialog(this, "Ukuran file terlalu besar! Maksimal 2 MB.",
                "File Terlalu Besar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Tampilkan path file di JTextField
        jTextField6.setText(selectedFile.getAbsolutePath());

        try {
            // Membaca file gambar sebagai byte array
            FileInputStream fis = new FileInputStream(selectedFile);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] buffer = new byte[1024];
            int length;
            
            while ((length = fis.read(buffer)) != -1) {
                baos.write(buffer, 0, length);
            }

            byte[] imageBytes = baos.toByteArray(); // Gambar dalam bentuk byte[]

            // Proses menyimpan byte[] imageBytes ke database di kolom gambar atau BLOB
            saveImageToDatabase(imageBytes);
            
            JOptionPane.showMessageDialog(this, "Foto berhasil diupload!", "Upload Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error dalam membaca file gambar: " + e.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pemilihan foto dibatalkan.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }
}

// Metode untuk menyimpan gambar ke database
private void saveImageToDatabase(byte[] imageBytes) {
    // Simpan gambar ke dalam database
    try {
        String sql = "INSERT INTO laporan (gambar) VALUES (?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setBytes(1, imageBytes);
        ps.executeUpdate();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan gambar ke database: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }



    
    }//GEN-LAST:event_uploadfotoActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuatLaporanPencemaranLaut().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login3;
    private javax.swing.JButton Login4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton uploadfoto;
    // End of variables declaration//GEN-END:variables
}
