/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import model.User;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.*;
import model.*;
import service.*;
import service.DatabaseConnection;

/**
 *
 * @author asus GK
 */
public class BUATLAPORANLOKASILAUT_1 extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JenisLaporan_U_1.class.getName());
    private User currentUser; // user yang sedang login
    private Connection conn;
    
    public BUATLAPORANLOKASILAUT_1(User user) {
        this.currentUser = user;
        initComponents();
        conn = DatabaseConnection.getConnection();
    }
    
    
    public BUATLAPORANLOKASILAUT_1() {
        conn = DatabaseConnection.getConnection();

        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kordinat = new javax.swing.JTextField();
        wilayah = new javax.swing.JTextField();
        namalokasi = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        kondisi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kordinat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kordinatActionPerformed(evt);
            }
        });
        getContentPane().add(kordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 560, 50));

        wilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wilayahActionPerformed(evt);
            }
        });
        getContentPane().add(wilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 560, 50));

        namalokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namalokasiActionPerformed(evt);
            }
        });
        getContentPane().add(namalokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 550, 50));

        next.setBackground(new java.awt.Color(0, 51, 153));
        next.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 180, 60));

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 180, 60));

        kondisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kondisiActionPerformed(evt);
            }
        });
        getContentPane().add(kondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 550, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Buatlaporanlokasilaut.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        String nama = namalokasi.getText().trim();
        String koordinatStr = kordinat.getText().trim();
        String wilayahStr = wilayah.getText().trim();
        String kondisiStr = kondisi.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama lokasi harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // koordinat boleh kosong (sesuai DB). Jika diisi, coba parse.
        Double koordinatVal = null;
        if (!koordinatStr.isEmpty()) {
            try {
                // gunakan Double karena kolom decimal(10,6) di DB
                koordinatVal = Double.parseDouble(koordinatStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Format koordinat tidak valid (contoh: -1.234567).", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        // Simpan ke tabel lokasi_laut
        String sql = "INSERT INTO lokasi_laut (nama_lokasi, koordinat, wilayah, kondisi_terakhir) VALUES (?, ?, ?, ?)";
        try (PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, nama);
            if (koordinatVal != null) {
                ps.setDouble(2, koordinatVal);
            } else {
                ps.setNull(2, Types.DECIMAL);
            }
            ps.setString(3, wilayahStr.isEmpty() ? null : wilayahStr);
            ps.setString(4, kondisiStr.isEmpty() ? null : kondisiStr);

            int affected = ps.executeUpdate();
            if (affected == 0) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data lokasi.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // ambil generated id_lokasi
            int idLokasi = -1;
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys != null && keys.next()) {
                    idLokasi = keys.getInt(1);
                }
            }

            if (idLokasi == -1) {
                JOptionPane.showMessageDialog(this, "Lokasi tersimpan tapi ID tidak terdeteksi.", "Info", JOptionPane.INFORMATION_MESSAGE);
                // tetap lanjutkan (jika mau), tapi sebaiknya stop
                return;
            }

            // lanjutkan ke JenisLaporan_U_2 dan oper idLokasi
            JOptionPane.showMessageDialog(this, "Lokasi tersimpan (ID: " + idLokasi + "). Lanjut pilih jenis laporan.");
            new JenisLaporan_U_2(currentUser, idLokasi).setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data lokasi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Insert lokasi error", e);
        }
    
    
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void namalokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namalokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namalokasiActionPerformed

    private void kordinatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kordinatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kordinatActionPerformed

    private void wilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wilayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wilayahActionPerformed

    private void kondisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kondisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kondisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BUATLAPORANLOKASILAUT().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kondisi;
    private javax.swing.JTextField kordinat;
    private javax.swing.JTextField namalokasi;
    private javax.swing.JButton next;
    private javax.swing.JTextField wilayah;
    // End of variables declaration//GEN-END:variables
}
