/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Image;
import java.io.*;
import java.sql.*;
import java.time.LocalDate;
import javax.imageio.ImageIO;
import javax.swing.*;
import model.User;
import service.DatabaseConnection;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.*;
import java.time.LocalDate;

/**
 *
 * @author asus GK
 */
public class BuatLaporanPenangkapanIkan_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(BuatLaporanPenangkapanIkan_1.class.getName());

    private User currentUser;
    private int lokasiId;
    private Connection conn;

    // Konstruktor dengan user & lokasi id
    public BuatLaporanPenangkapanIkan_1(User user, int lokasiId) {
        this.currentUser = user;
        this.lokasiId = lokasiId;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
    }

    // Konstruktor default (tidak disarankan)
    public BuatLaporanPenangkapanIkan_1() {
        this.conn = DatabaseConnection.getConnection();
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 570, 50));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 560, 60));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 550, 60));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 80, 560, 60));

        send.setBackground(new java.awt.Color(0, 51, 153));
        send.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 180, 60));

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/penangkapanilegal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
        String jenisKapal = jTextField1.getText().trim();
        String alatTangkap = jTextField2.getText().trim();
        String zonaPenangkapan = jTextField3.getText().trim();
        String pelanggaran = jTextField4.getText().trim();

        if (jenisKapal.isEmpty() || alatTangkap.isEmpty() || zonaPenangkapan.isEmpty() || pelanggaran.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua field!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 1️⃣ Simpan ke tabel laporan utama
            String laporanSql = "INSERT INTO laporan (id_pelapor, id_lokasi, tanggal_lapor, deskripsi, status_laporan, jenis_laporan) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement ps1 = conn.prepareStatement(laporanSql, Statement.RETURN_GENERATED_KEYS);
            ps1.setInt(1, currentUser.getIdUser());
            ps1.setInt(2, lokasiId);
            ps1.setDate(3, Date.valueOf(LocalDate.now()));
            ps1.setString(4, pelanggaran);
            ps1.setString(5, "Menunggu");
            ps1.setString(6, "Penangkapan Ikan");
            ps1.executeUpdate();

            ResultSet rs = ps1.getGeneratedKeys();
            int idLaporan = 0;
            if (rs.next()) {
                idLaporan = rs.getInt(1);
            }

            // 2️⃣ Simpan ke tabel laporan_penangkapan_ikan
            String detailSql = "INSERT INTO laporan_penangkapan_ikan (jenis_kapal, alat_tangkap, zona_penangkapan, pelanggaran, id_laporan) "
                    + "VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps2 = conn.prepareStatement(detailSql);
            ps2.setString(1, jenisKapal);
            ps2.setString(2, alatTangkap);
            ps2.setString(3, zonaPenangkapan);
            ps2.setString(4, pelanggaran);
            ps2.setInt(5, idLaporan);
            ps2.executeUpdate();

            JOptionPane.showMessageDialog(this, "Laporan Penangkapan Ikan berhasil dikirim!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            new Menu_Masyarakat(currentUser).setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "DB Error", e);
        }
    

    
    }//GEN-LAST:event_sendActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    
    }//GEN-LAST:event_backActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuatLaporanPenangkapanIkan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
