/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.sql.*;
import javax.swing.*;
import model.User;
import service.DatabaseConnection;

public class BuatLaporanPenangkapanIkan extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(BuatLaporanPenangkapanIkan.class.getName());

    private User currentUser;
    private int lokasiId;
    private Connection conn;

    // 🔹 Konstruktor default
    public BuatLaporanPenangkapanIkan() {
        initComponents();
        conn = DatabaseConnection.getConnection();
    }

    // 🔹 Konstruktor menerima user dan id lokasi dari JenisLaporan_A
    public BuatLaporanPenangkapanIkan(User user, int lokasiId) {
        this.currentUser = user;
        this.lokasiId = lokasiId;
        initComponents();
        conn = DatabaseConnection.getConnection();
        System.out.println("✅ BuatLaporanPenangkapanIkan menerima id_lokasi: " + lokasiId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        send = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 560, 50));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 560, 60));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 550, 60));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 550, 60));

        send.setBackground(new java.awt.Color(0, 51, 153));
        send.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        send.setForeground(new java.awt.Color(255, 255, 255));
        send.setText("Send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        getContentPane().add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 180, 60));

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 180, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/penangkapanilegal.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
                                             
        String deskripsi = jTextField4.getText().trim();
        String jenisIkan = jTextField1.getText().trim();
        String jumlahTangkap = jTextField2.getText().trim();
        String alatTangkap = jTextField3.getText().trim();

        if (deskripsi.isEmpty() || jenisIkan.isEmpty() || jumlahTangkap.isEmpty() || alatTangkap.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO laporan (id_pelapor, id_lokasi, tanggal_lapor, deskripsi, jenis_laporan, status_laporan) "
                   + "VALUES (?, ?, ?, ?, ?, ?)";

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, currentUser.getIdUser());
            ps.setInt(2, lokasiId);
            ps.setDate(3, java.sql.Date.valueOf(java.time.LocalDate.now()));
            ps.setString(4, deskripsi + " | Jenis Ikan: " + jenisIkan + ", Jumlah: " + jumlahTangkap + ", Alat: " + alatTangkap);
            ps.setString(5, "Penangkapan Ikan");
            ps.setString(6, "Menunggu");

            int rows = ps.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "✅ Laporan penangkapan ikan berhasil dikirim!");
                new Menu_Admin(currentUser).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Gagal mengirim laporan!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "SQL Error", e);
            JOptionPane.showMessageDialog(this, "Kesalahan SQL: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sendActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new JenisLaporan_A(currentUser, lokasiId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuatLaporanPenangkapanIkan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
