/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import model.User;
import javax.swing.*;
import java.sql.*;
import service.DatabaseConnection;

/**
 *
 * @author asus GK
 */
public class BUATLAPORANLOKASILAUT extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(BUATLAPORANLOKASILAUT.class.getName());
    private User currentUser;
    private Connection conn;

    public BUATLAPORANLOKASILAUT(User user) {
        this.currentUser = user;
        initComponents();
        conn = DatabaseConnection.getConnection();
    }

    public BUATLAPORANLOKASILAUT() {
        initComponents();
        conn = DatabaseConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kordinat = new javax.swing.JTextField();
        wilayah = new javax.swing.JTextField();
        namalokasi = new javax.swing.JTextField();
        Login3 = new javax.swing.JButton();
        Login4 = new javax.swing.JButton();
        kondisi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(kordinat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 560, 50));

        wilayah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wilayahActionPerformed(evt);
            }
        });
        getContentPane().add(wilayah, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 560, 50));

        namalokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namalokasiActionPerformed(evt);
            }
        });
        getContentPane().add(namalokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 550, 50));

        Login3.setBackground(new java.awt.Color(0, 51, 153));
        Login3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Next");
        Login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login3ActionPerformed(evt);
            }
        });
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 180, 60));

        Login4.setBackground(new java.awt.Color(0, 51, 153));
        Login4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Login4.setForeground(new java.awt.Color(255, 255, 255));
        Login4.setText("Back");
        Login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login4ActionPerformed(evt);
            }
        });
        getContentPane().add(Login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 180, 60));
        getContentPane().add(kondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 550, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Buatlaporanlokasilaut.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login3ActionPerformed
        // TODO add your handling code here:
        String nama = namalokasi.getText().trim();
        String koordinatStr = kordinat.getText().trim();
        String wilayahStr = wilayah.getText().trim();
        String kondisiStr = kondisi.getText().trim();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama lokasi harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Double koordinatVal = null;
        if (!koordinatStr.isEmpty()) {
            try {
                koordinatVal = Double.parseDouble(koordinatStr);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Format koordinat tidak valid (contoh: -1.234567).", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        // Simpan ke tabel lokasi_laut
        String sql = "INSERT INTO lokasi_laut (nama_lokasi, koordinat, wilayah, kondisi_terakhir) VALUES (?, ?, ?, ?)";
        try (PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, nama);
            if (koordinatVal != null) {
                ps.setDouble(2, koordinatVal);
            } else {
                ps.setNull(2, Types.DECIMAL);
            }
            ps.setString(3, wilayahStr.isEmpty() ? null : wilayahStr);
            ps.setString(4, kondisiStr.isEmpty() ? null : kondisiStr);

            int affected = ps.executeUpdate();
            if (affected == 0) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data lokasi.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int idLokasi = -1;
            try (ResultSet keys = ps.getGeneratedKeys()) {
                if (keys != null && keys.next()) {
                    idLokasi = keys.getInt(1);
                }
            }

            JOptionPane.showMessageDialog(this,
                    "Lokasi berhasil disimpan!\nID Lokasi: " + idLokasi + "\nLanjut ke pemilihan jenis laporan.");

            // ✅ Kirim idLokasi ke JenisLaporan_A
            new JenisLaporan_A(currentUser, idLokasi).setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data lokasi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            logger.log(java.util.logging.Level.SEVERE, "Insert lokasi error", e);
        }
    

    
    }//GEN-LAST:event_Login3ActionPerformed

    private void Login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login4ActionPerformed
        // TODO add your handling code here:
        new Menu_Admin(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login4ActionPerformed

    private void namalokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namalokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namalokasiActionPerformed

    private void wilayahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wilayahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wilayahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BUATLAPORANLOKASILAUT().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login3;
    private javax.swing.JButton Login4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kondisi;
    private javax.swing.JTextField kordinat;
    private javax.swing.JTextField namalokasi;
    private javax.swing.JTextField wilayah;
    // End of variables declaration//GEN-END:variables
}
