/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.Connection;
import model.User;
import service.DatabaseConnection;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Logger;

public class Caritindaklanjut extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(Caritindaklanjut.class.getName()); // Inisialisasi logger
    private User currentUser; // === Simpan data user yang login ===
    private Connection conn;

    public Caritindaklanjut() {
        initComponents();
    }

    public Caritindaklanjut(User user) {
        this.currentUser = user; // Simpan data user yang sedang login
        this.conn = DatabaseConnection.getConnection();
        initComponents();
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Login3 = new javax.swing.JButton();
        Login4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 560, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, -1, -1));

        Login3.setBackground(new java.awt.Color(0, 51, 153));
        Login3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Search");
        Login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login3ActionPerformed(evt);
            }
        });
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 270, 80));

        Login4.setBackground(new java.awt.Color(0, 51, 153));
        Login4.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Login4.setForeground(new java.awt.Color(255, 255, 255));
        Login4.setText("Back");
        Login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login4ActionPerformed(evt);
            }
        });
        getContentPane().add(Login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 260, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/CariTindakLanjut_1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login3ActionPerformed
        // TODO add your handling code here:
        String dendaText = jTextField5.getText().trim();
        
        // Jika input kosong, tampilkan pesan peringatan
        if (dendaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan nominal denda yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                // Mengubah input menjadi nilai decimal untuk pencarian
                double nominalDenda = Double.parseDouble(dendaText);
                // Lakukan pencarian berdasarkan nominal_denda
                loadData(nominalDenda);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Nominal denda harus berupa angka.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void loadData(double nominalDenda) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Tindak");
        model.addColumn("ID Laporan");
        model.addColumn("Tanggal Tindak");
        model.addColumn("Hasil Tindak");
        model.addColumn("Nominal Denda");
        model.addColumn("Status Tindakan");

        try {
            // Query pencarian berdasarkan nominal_denda
            String sql = "SELECT id_tindak, id_laporan, tanggal_tindak, hasil_tindak, nominal_denda, status_tindakan FROM tindak_lanjut WHERE nominal_denda = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setDouble(1, nominalDenda); // Menggunakan nominal_denda untuk pencarian
            ResultSet rs = ps.executeQuery();

            // Mengisi tabel dengan hasil pencarian
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_tindak"),
                    rs.getInt("id_laporan"),
                    rs.getDate("tanggal_tindak"),
                    rs.getString("hasil_tindak"),
                    rs.getDouble("nominal_denda"),
                    rs.getString("status_tindakan")
                });
            }
            jTable1.setModel(model); // Menampilkan model pada jTable

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data tindak lanjut", e);
            JOptionPane.showMessageDialog(this, "Kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_Login3ActionPerformed

    private void Login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login4ActionPerformed
        // TODO add your handling code here:
        new Menu_Admin(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        // Mendapatkan input nominal denda dari JTextField
        
        
        
    
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
         
        }
        //</editor-fold>

        /* Create and display the form */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login3;
    private javax.swing.JButton Login4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
