/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import model.User;
import service.DatabaseConnection;

public class Hapuslaporanadmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hapuslaporanadmin.class.getName());
    private User currentUser;  // Store current user
    private Connection conn;

    // Constructor to accept the current user
    public Hapuslaporanadmin(User user) {
        this.currentUser = user;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
        loadData();
    }

    // Load data into the table
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Laporan");
        model.addColumn("Tanggal Lapor");
        model.addColumn("Deskripsi");
        model.addColumn("Status Laporan");

        try {
            String sql = "SELECT id_laporan, tanggal_lapor, deskripsi, status_laporan FROM laporan";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                        rs.getInt("id_laporan"),
                        rs.getDate("tanggal_lapor"),
                        rs.getString("deskripsi"),
                        rs.getString("status_laporan")
                });
            }
            jTable1.setModel(model); // Set the table model
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data laporan", e);
            JOptionPane.showMessageDialog(this, "Kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Method to delete a report
    private void deleteReport(int idLaporan) {
        try {
            String sql = "DELETE FROM laporan WHERE id_laporan = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idLaporan);
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Laporan berhasil dihapus!");
                loadData(); // Reload data after deletion
            } else {
                JOptionPane.showMessageDialog(this, "Laporan tidak ditemukan!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menghapus laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Login4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login3.setBackground(new java.awt.Color(0, 51, 153));
        Login3.setFont(new java.awt.Font("STHupo", 0, 14)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Hapus");
        Login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login3ActionPerformed(evt);
            }
        });
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 530, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 1020, 460));

        Login4.setBackground(new java.awt.Color(0, 51, 153));
        Login4.setFont(new java.awt.Font("STHupo", 0, 14)); // NOI18N
        Login4.setForeground(new java.awt.Color(255, 255, 255));
        Login4.setText("Back");
        Login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login4ActionPerformed(evt);
            }
        });
        getContentPane().add(Login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 130, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HapusLaporanPencemaran.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1) {
            // Get the selected report ID
            int reportId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
            deleteReport(reportId);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang akan dihapus terlebih dahulu!");
        }
    
    }//GEN-LAST:event_Login3ActionPerformed

    private void Login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login4ActionPerformed
        // TODO add your handling code here:
        new Menu_Admin(currentUser).setVisible(true); // Go back to Menu_Admin
        this.dispose();
    }//GEN-LAST:event_Login4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login3;
    private javax.swing.JButton Login4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
