/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import model.User;
import service.DatabaseConnection;

public class Hapuslaporanpenangkapan1_1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hapuslaporanpenangkapan1_1.class.getName());
    private User currentUser;
    private Connection conn;

    public Hapuslaporanpenangkapan1_1(User user) {
        this.currentUser = user;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
        loadTableData();
    }

    public Hapuslaporanpenangkapan1_1() {
        this.conn = DatabaseConnection.getConnection();
        initComponents();
    }

    // 🔹 Menampilkan data laporan penangkapan milik user login
    private void loadTableData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Laporan");
        model.addColumn("Tanggal Lapor");
        model.addColumn("Deskripsi");
        model.addColumn("Jenis Kapal");
        model.addColumn("Alat Tangkap");
        model.addColumn("Zona Penangkapan");
        model.addColumn("Pelanggaran");
        model.addColumn("Status");

        try {
            String sql = """
                SELECT l.id_laporan, l.tanggal_lapor, l.deskripsi,
                       p.jenis_kapal, p.alat_tangkap, p.zona_penangkapan, p.pelanggaran,
                       l.status_laporan
                FROM laporan l
                JOIN laporan_penangkapan_ikan p ON l.id_laporan = p.id_laporan
                WHERE l.id_pelapor = ? AND l.jenis_laporan = 'Penangkapan Ikan'
                ORDER BY l.tanggal_lapor DESC
            """;
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, currentUser.getIdUser());
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_laporan"),
                    rs.getDate("tanggal_lapor"),
                    rs.getString("deskripsi"),
                    rs.getString("jenis_kapal"),
                    rs.getString("alat_tangkap"),
                    rs.getString("zona_penangkapan"),
                    rs.getString("pelanggaran"),
                    rs.getString("status_laporan")
                });
            }
            jTable1.setModel(model);
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal load data laporan", e);
            JOptionPane.showMessageDialog(this, "Kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login5 = new javax.swing.JButton();
        Login3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login5.setBackground(new java.awt.Color(0, 51, 153));
        Login5.setFont(new java.awt.Font("STHupo", 0, 14)); // NOI18N
        Login5.setForeground(new java.awt.Color(255, 255, 255));
        Login5.setText("back");
        Login5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login5ActionPerformed(evt);
            }
        });
        getContentPane().add(Login5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, 130, 40));

        Login3.setBackground(new java.awt.Color(0, 51, 153));
        Login3.setFont(new java.awt.Font("STHupo", 0, 14)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Hapus");
        Login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login3ActionPerformed(evt);
            }
        });
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 530, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 940, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/HapusLaporanPenangkapan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idLaporan = (int) jTable1.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus laporan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            String sql = "DELETE FROM laporan WHERE id_laporan = ? AND id_pelapor = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idLaporan);
            ps.setInt(2, currentUser.getIdUser());
            int affected = ps.executeUpdate();

            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "Laporan berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                loadTableData();
            } else {
                JOptionPane.showMessageDialog(this, "Anda tidak berhak menghapus laporan ini!", "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal hapus laporan", e);
            JOptionPane.showMessageDialog(this, "Kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_Login3ActionPerformed

    private void Login5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login5ActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Hapuslaporanpenangkapan1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login3;
    private javax.swing.JButton Login5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
