/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import model.User;
import service.DatabaseConnection;
/**
 *
 * @author asus GK
 */
public class JenisLaporan_A_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(JenisLaporan_A.class.getName());

    private User currentUser;
    private int lokasiId;

    public JenisLaporan_A_1() {
        initComponents();
    }

    // Konstruktor menerima user dan id lokasi dari form sebelumnya
    public JenisLaporan_A_1(User user, int lokasiId) {
        this.currentUser = user;
        this.lokasiId = lokasiId;
        initComponents();
        System.out.println("✅ JenisLaporan_A menerima id_lokasi: " + lokasiId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        Login5 = new javax.swing.JButton();
        Login6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 102));
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 80, 60));

        Login5.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        Login5.setForeground(new java.awt.Color(0, 102, 102));
        Login5.setText("Penangkapan Ikan");
        Login5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login5ActionPerformed(evt);
            }
        });
        getContentPane().add(Login5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 230, 60));

        Login6.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        Login6.setForeground(new java.awt.Color(0, 102, 102));
        Login6.setText(" Pencemaran Laut");
        Login6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login6ActionPerformed(evt);
            }
        });
        getContentPane().add(Login6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 230, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/JenisLaporan.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login5ActionPerformed
        // TODO add your handling code here:
        new BuatLaporanPenangkapanIkan(currentUser, lokasiId).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_Login5ActionPerformed

    private void Login6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login6ActionPerformed
        // TODO add your handling code here:
        new BuatLaporanPencemaranLaut(currentUser, lokasiId).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login6ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            new Menu_Admin(currentUser).setVisible(true);
        } else {
            new Menu_Admin().setVisible(true); // fallback
        }
        this.dispose();
                      

    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JenisLaporan_A().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login5;
    private javax.swing.JButton Login6;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
