/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import model.User;
import service.DatabaseConnection;

public class JenisLaporan_U_2_1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(JenisLaporan_U_2_1.class.getName());

    private User currentUser;
    private Connection conn;

    public JenisLaporan_U_2_1(User user) {
        this.currentUser = user;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
    }

    public JenisLaporan_U_2_1() {
        conn = DatabaseConnection.getConnection();
        initComponents();
    }
    

    
    // Konstruktor default (tidak disarankan)
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penangkapan = new javax.swing.JButton();
        pencemaran1 = new javax.swing.JButton();
        pencemaran = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        penangkapan.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        penangkapan.setForeground(new java.awt.Color(0, 102, 102));
        penangkapan.setText("Penangkapan Ikan");
        penangkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penangkapanActionPerformed(evt);
            }
        });
        getContentPane().add(penangkapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 210, 60));

        pencemaran1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        pencemaran1.setForeground(new java.awt.Color(0, 102, 102));
        pencemaran1.setText("back");
        pencemaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencemaran1ActionPerformed(evt);
            }
        });
        getContentPane().add(pencemaran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 80, 60));

        pencemaran.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        pencemaran.setForeground(new java.awt.Color(0, 102, 102));
        pencemaran.setText(" Pencemaran Laut");
        pencemaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencemaranActionPerformed(evt);
            }
        });
        getContentPane().add(pencemaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 210, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/JenisLaporan.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void penangkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penangkapanActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
            JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.WARNING_MESSAGE);
            new LOGIN().setVisible(true);
            this.dispose();
            return;
        }

        // Tampilkan daftar laporan dalam JTable popup
        try {
            String sql = """
                SELECT l.id_laporan, l.tanggal_lapor, l.deskripsi, p.jenis_kapal, p.zona_penangkapan
                FROM laporan l
                JOIN laporan_penangkapan_ikan p ON l.id_laporan = p.id_laporan
                WHERE p.id_laporan = ?
            """;

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, currentUser.getIdUser());
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Laporan");
            model.addColumn("Tanggal Lapor");
            model.addColumn("Jenis Kapal");
            model.addColumn("Zona Penangkapan");
            model.addColumn("Deskripsi");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_laporan"),
                    rs.getDate("tanggal_lapor"),
                    rs.getString("jenis_kapal"),
                    rs.getString("zona_penangkapan"),
                    rs.getString("deskripsi")
                });
            }

            JTable table = new JTable(model);
            JScrollPane scroll = new JScrollPane(table);
            scroll.setPreferredSize(new java.awt.Dimension(600, 250));

            int option = JOptionPane.showConfirmDialog(
                    this, scroll,
                    "Pilih Laporan Penangkapan yang Akan Diperbarui",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.PLAIN_MESSAGE
            );

            if (option == JOptionPane.OK_OPTION && table.getSelectedRow() != -1) {
                int idLaporan = (int) table.getValueAt(table.getSelectedRow(), 0);
                new Perbaruilaporanpenangkapan_1(currentUser, idLaporan).setVisible(true);
                this.dispose();
            }

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Kesalahan saat memuat laporan", e);
            JOptionPane.showMessageDialog(this, "Gagal mengambil data laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_penangkapanActionPerformed

    private void pencemaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencemaranActionPerformed
        // TODO add your handling code here:
        if (currentUser == null) {
    JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.WARNING_MESSAGE);
    new LOGIN().setVisible(true);
    this.dispose();
    return;
}

try {
    // SQL Query untuk mengambil data laporan berdasarkan id_pelapor
    String sql = """
        SELECT l.id_laporan, l.tanggal_lapor, l.deskripsi, p.sumber_limbah, p.jenis_limbah, p.tingkat_pencemaran
        FROM laporan l
        JOIN laporan_pencemaran p ON l.id_laporan = p.id_laporan
        WHERE p.id_laporan = ?;
    """;

    // Prepare Statement untuk query
    PreparedStatement ps = conn.prepareStatement(sql);
    ps.setInt(1, currentUser.getIdUser());  // Set user ID pada query berdasarkan ID pelapor
    ResultSet rs = ps.executeQuery();

    // Periksa apakah data ditemukan
    if (!rs.next()) {
        System.out.println("No data found for this user.");
        JOptionPane.showMessageDialog(this, "Tidak ada laporan yang ditemukan.", "Info", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // DefaultTableModel untuk menampilkan data di JTable
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Laporan");
    model.addColumn("Tanggal Lapor");
    model.addColumn("Sumber Limbah");
    model.addColumn("Jenis Limbah");
    model.addColumn("Tingkat Pencemaran");
    model.addColumn("Deskripsi");

    // Tambahkan data ke model
    do {
        System.out.println("Data found: " + rs.getInt("id_laporan"));
        model.addRow(new Object[]{
            rs.getInt("id_laporan"),
            rs.getDate("tanggal_lapor"),
            rs.getString("sumber_limbah"),
            rs.getString("jenis_limbah"),
            rs.getString("tingkat_pencemaran"),
            rs.getString("deskripsi")
        });
    } while (rs.next());

    // Buat JTable dan JScrollPane untuk menampilkan data
    JTable table = new JTable(model);
    JScrollPane scroll = new JScrollPane(table);
    scroll.setPreferredSize(new java.awt.Dimension(600, 250));

    // Menampilkan dialog dengan JTable untuk memilih laporan yang akan diperbarui
    int option = JOptionPane.showConfirmDialog(
            this, scroll,
            "Pilih Laporan Pencemaran yang Akan Diperbarui",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
    );

    // Jika pengguna memilih OK dan memilih laporan
    if (option == JOptionPane.OK_OPTION && table.getSelectedRow() != -1) {
        int idLaporan = (int) table.getValueAt(table.getSelectedRow(), 0);
        new Perbaruilaporanpencemaran_1(currentUser, idLaporan).setVisible(true);
        this.dispose();
    }

} catch (SQLException e) {
    // Menangani kesalahan SQL dan menampilkan pesan kesalahan
    logger.log(java.util.logging.Level.SEVERE, "Kesalahan saat memuat laporan pencemaran", e);
    JOptionPane.showMessageDialog(this, "Gagal mengambil data laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        
    
    }//GEN-LAST:event_pencemaranActionPerformed

    private void pencemaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencemaran1ActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pencemaran1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JenisLaporan_U().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton penangkapan;
    private javax.swing.JButton pencemaran;
    private javax.swing.JButton pencemaran1;
    // End of variables declaration//GEN-END:variables
}
