/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author asus GK
 */
public class JenisLaporan_U extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JenisLaporan_U.class.getName());

    /**
     * Creates new form BuatLaporan_A
     */
    public JenisLaporan_U() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login5 = new javax.swing.JButton();
        pencemaran1 = new javax.swing.JButton();
        Login6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login5.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        Login5.setForeground(new java.awt.Color(0, 102, 102));
        Login5.setText("Penangkapan Ikan");
        Login5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login5ActionPerformed(evt);
            }
        });
        getContentPane().add(Login5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 210, 60));

        pencemaran1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        pencemaran1.setForeground(new java.awt.Color(0, 102, 102));
        pencemaran1.setText("back");
        pencemaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencemaran1ActionPerformed(evt);
            }
        });
        getContentPane().add(pencemaran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 80, 60));

        Login6.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        Login6.setForeground(new java.awt.Color(0, 102, 102));
        Login6.setText(" Pencemaran Laut");
        Login6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login6ActionPerformed(evt);
            }
        });
        getContentPane().add(Login6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 210, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/project_akhir/JenisLaporan.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login5ActionPerformed

    private void Login6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Login6ActionPerformed

    private void pencemaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencemaran1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_pencemaran1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JenisLaporan_U().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login5;
    private javax.swing.JButton Login6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton pencemaran1;
    // End of variables declaration//GEN-END:variables
}
