/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.*;
import java.sql.*;
import model.*;
import service.*;

/**
 *
 * @author asus GK
 */
public class JenisLaporan_U_1 extends javax.swing.JFrame {
    
   
    /**
     * Creates new form BuatLaporan_A
     */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JenisLaporan_U_1.class.getName());
    private User currentUser; // user yang sedang login

    // Konstruktor baru yang menerima user login
    public JenisLaporan_U_1(User user) {
        this.currentUser = user;
        initComponents();
    }
    
    public JenisLaporan_U_1() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penangkapan = new javax.swing.JButton();
        pencemaran1 = new javax.swing.JButton();
        pencemaran = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        penangkapan.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        penangkapan.setForeground(new java.awt.Color(0, 102, 102));
        penangkapan.setText("Penangkapan Ikan");
        penangkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penangkapanActionPerformed(evt);
            }
        });
        getContentPane().add(penangkapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 210, 60));

        pencemaran1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        pencemaran1.setForeground(new java.awt.Color(0, 102, 102));
        pencemaran1.setText("back");
        pencemaran1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencemaran1ActionPerformed(evt);
            }
        });
        getContentPane().add(pencemaran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 80, 60));

        pencemaran.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        pencemaran.setForeground(new java.awt.Color(0, 102, 102));
        pencemaran.setText(" Pencemaran Laut");
        pencemaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencemaranActionPerformed(evt);
            }
        });
        getContentPane().add(pencemaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 210, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/JenisLaporan.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void penangkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penangkapanActionPerformed
        // TODO add your handling code here:
         if (currentUser != null) {
        new Hapuslaporanpenangkapan1_1(currentUser).setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
        new LOGIN().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_penangkapanActionPerformed

    private void pencemaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencemaranActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            new HapuslaporanPencemaran_1(currentUser).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, 
                "User belum terdeteksi, harap login terlebih dahulu!", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            new LOGIN().setVisible(true);
        }
        this.dispose();
        
        
        
    }//GEN-LAST:event_pencemaranActionPerformed

    private void pencemaran1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencemaran1ActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pencemaran1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JenisLaporan_U_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton penangkapan;
    private javax.swing.JButton pencemaran;
    private javax.swing.JButton pencemaran1;
    // End of variables declaration//GEN-END:variables
}
