/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import model.User;

/**
 *
 * @author asus GK
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import model.User;
import service.DatabaseConnection;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.*;
import java.time.LocalDate;
import java.io.FileInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

public class Lihatlaporanpencemaran_22 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(Lihatlaporanpencemaran_22.class.getName());
    
    private User currentUser; 
    private Connection conn;

    // Konstruktor untuk menerima user yang sedang login
    public Lihatlaporanpencemaran_22(User user) {
        this.currentUser = user;
        initComponents();
        this.conn = DatabaseConnection.getConnection();
        loadData();
    }

    // Method untuk load data laporan dan gambar
    private void loadData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Laporan");
        model.addColumn("ID Pelapor");
        model.addColumn("ID Lokasi");
        model.addColumn("Tanggal Lapor");
        model.addColumn("Deskripsi");
        model.addColumn("Status Laporan");
        model.addColumn("Jenis Laporan");
        model.addColumn("Foto Bukti");

        try {
            String sql = "SELECT id_laporan, id_pelapor, id_lokasi, tanggal_lapor, deskripsi, status_laporan, jenis_laporan, foto_bukti FROM laporan";
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                byte[] imgBytes = rs.getBytes("foto_bukti"); // Ambil gambar dari BLOB
                ImageIcon imageIcon = null;
                if (imgBytes != null) {
                    imageIcon = new ImageIcon(imgBytes);
                }
                
                model.addRow(new Object[]{
                    rs.getInt("id_laporan"),
                    rs.getInt("id_pelapor"),
                    rs.getInt("id_lokasi"),
                    rs.getDate("tanggal_lapor"),
                    rs.getString("deskripsi"),
                    rs.getString("status_laporan"),
                    rs.getString("jenis_laporan"),
                    imageIcon != null ? imageIcon : null // Set gambar ke tabel
                });
            }
            jTable1.setModel(model);

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data laporan", e);
            JOptionPane.showMessageDialog(this, "Kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // 🔹 Koneksi ke database
    // 🔹 Load data dari tabel user
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login4 = new javax.swing.JButton();
        Login3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login4.setBackground(new java.awt.Color(0, 51, 153));
        Login4.setFont(new java.awt.Font("STHupo", 0, 14)); // NOI18N
        Login4.setForeground(new java.awt.Color(255, 255, 255));
        Login4.setText("lihat foto");
        Login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login4ActionPerformed(evt);
            }
        });
        getContentPane().add(Login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 540, 130, 40));

        Login3.setBackground(new java.awt.Color(0, 51, 153));
        Login3.setFont(new java.awt.Font("STHupo", 0, 14)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Back");
        Login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login3ActionPerformed(evt);
            }
        });
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 1020, 460));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lihatlaporanpencemaran.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login3ActionPerformed
        // TODO add your handling code here:

            new PilihMenulihat(currentUser).setVisible(true);

        this.dispose();
    
    }//GEN-LAST:event_Login3ActionPerformed

    private void Login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login4ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        int reportId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        // Mengambil gambar dari database berdasarkan ID laporan
        byte[] imageBytes = getImageFromDatabase(reportId);
        if (imageBytes != null) {
            // Mengonversi byte[] menjadi ImageIcon
            ImageIcon imageIcon = new ImageIcon(imageBytes);
            // Membuat label untuk menampilkan gambar
            JLabel label = new JLabel(imageIcon);
            JOptionPane.showMessageDialog(this, label, "Foto Bukti Pencemaran", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada gambar untuk laporan ini.", 
                "Tidak Ada Gambar", JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih laporan untuk menampilkan gambar terlebih dahulu!", 
            "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
}

// Metode untuk mengambil gambar dari database berdasarkan ID laporan
private byte[] getImageFromDatabase(int reportId) {
    byte[] imageBytes = null;
    try {
        // Query untuk mengambil gambar berdasarkan ID laporan
        String sql = "SELECT foto_bukti FROM laporan WHERE id_laporan = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, reportId);
        ResultSet rs = ps.executeQuery();

        // Jika gambar ditemukan, ambil data gambar sebagai byte[]
        if (rs.next()) {
            imageBytes = rs.getBytes("foto_bukti"); // Kolom foto_bukti
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil gambar dari database: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    return imageBytes;



    

        
    }//GEN-LAST:event_Login4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Lihatlaporanpencemaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login3;
    private javax.swing.JButton Login4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
