/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.JOptionPane;
import model.User;
import javax.swing.*;


/**
 *
 * @author asus GK
 */
public class Menu_Admin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu_Admin.class.getName());
    private User currentUser; // === Simpan data user yang login ===

    /**
     * Konstruktor default (tidak disarankan digunakan langsung)
     */
    public Menu_Admin() {
        initComponents();
    }
    public Menu_Admin(User user) {
        this.currentUser = user; // Simpan data user yang sedang login
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hapus = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        back = new javax.swing.JButton();
        perbarui = new javax.swing.JButton();
        tindaklanjut = new javax.swing.JButton();
        buat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hapus.setBackground(new java.awt.Color(0, 204, 204));
        hapus.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        hapus.setForeground(new java.awt.Color(255, 255, 255));
        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 240, 70));

        cari.setBackground(new java.awt.Color(0, 204, 204));
        cari.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        cari.setForeground(new java.awt.Color(255, 255, 255));
        cari.setText("Cari ");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 240, 70));

        lihat.setBackground(new java.awt.Color(0, 204, 204));
        lihat.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        lihat.setForeground(new java.awt.Color(255, 255, 255));
        lihat.setText("Lihat Laporan");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });
        getContentPane().add(lihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 240, 70));

        back.setBackground(new java.awt.Color(0, 153, 153));
        back.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 240, 70));

        perbarui.setBackground(new java.awt.Color(0, 204, 204));
        perbarui.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        perbarui.setForeground(new java.awt.Color(255, 255, 255));
        perbarui.setText("Perbarui ");
        perbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbaruiActionPerformed(evt);
            }
        });
        getContentPane().add(perbarui, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 240, 70));

        tindaklanjut.setBackground(new java.awt.Color(0, 204, 204));
        tindaklanjut.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        tindaklanjut.setForeground(new java.awt.Color(255, 255, 255));
        tindaklanjut.setText("Tindak lanjuti");
        tindaklanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tindaklanjutActionPerformed(evt);
            }
        });
        getContentPane().add(tindaklanjut, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 190, 70));

        buat.setBackground(new java.awt.Color(0, 204, 204));
        buat.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        buat.setForeground(new java.awt.Color(255, 255, 255));
        buat.setText("Buat Laporan");
        buat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatActionPerformed(evt);
            }
        });
        getContentPane().add(buat, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 240, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MenuAdmin.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            // 🔗 Langsung menuju PilihMenulihat
            new PilihMenuhapus(currentUser).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
            new LOGIN().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void buatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            new BUATLAPORANLOKASILAUT(currentUser).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
            new LOGIN().setVisible(true);
        }
        this.dispose();
        
    }//GEN-LAST:event_buatActionPerformed

    private void perbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbaruiActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
        new PilihMenu(currentUser).setVisible(true); // buka PilihMenu
        this.dispose(); // tutup Menu_Admin
    } else {
        JOptionPane.showMessageDialog(this, 
            "User belum login!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        new LOGIN().setVisible(true);
        this.dispose();
    }

    }//GEN-LAST:event_perbaruiActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            // 🔗 Langsung menuju PilihMenulihat
            new PilihMenu4_1_1a(currentUser).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
            new LOGIN().setVisible(true);
            this.dispose();
        }
        
    

    }//GEN-LAST:event_lihatActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            // 🔗 Langsung menuju PilihMenulihat
            new Pilihmenucari(currentUser).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
            new LOGIN().setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_cariActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    new LOGIN().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void tindaklanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tindaklanjutActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
        new BUATLAPORANTINDAKLANJUT(currentUser).setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
        new LOGIN().setVisible(true);
    }
    }//GEN-LAST:event_tindaklanjutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu_Admin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton buat;
    private javax.swing.JButton cari;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lihat;
    private javax.swing.JButton perbarui;
    private javax.swing.JButton tindaklanjut;
    // End of variables declaration//GEN-END:variables
}
