/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import model.User;

/**
 *
 * @author asus GK
 */
public class Menu_Masyarakat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu_Masyarakat.class.getName());
    private User currentUser; // Menyimpan user login

    // Konstruktor utama (dengan user login)
    public Menu_Masyarakat(User user) {
        this.currentUser = user;
        initComponents();
    }

    // Konstruktor default (testing manual)
    public Menu_Masyarakat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        buat1 = new javax.swing.JButton();
        lihat1 = new javax.swing.JButton();
        perbarui1 = new javax.swing.JButton();
        cari1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(0, 153, 153));
        back.setFont(new java.awt.Font("STHupo", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 130, 50));

        hapus1.setBackground(new java.awt.Color(0, 204, 204));
        hapus1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        hapus1.setForeground(new java.awt.Color(255, 255, 255));
        hapus1.setText("Hapus Laporan");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });
        getContentPane().add(hapus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 230, 60));

        buat1.setBackground(new java.awt.Color(0, 204, 204));
        buat1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        buat1.setForeground(new java.awt.Color(255, 255, 255));
        buat1.setText("Buat Laporan");
        buat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buat1ActionPerformed(evt);
            }
        });
        getContentPane().add(buat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 230, 60));

        lihat1.setBackground(new java.awt.Color(0, 204, 204));
        lihat1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        lihat1.setForeground(new java.awt.Color(255, 255, 255));
        lihat1.setText("Lihat Laporan");
        lihat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihat1ActionPerformed(evt);
            }
        });
        getContentPane().add(lihat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 230, 60));

        perbarui1.setBackground(new java.awt.Color(0, 204, 204));
        perbarui1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        perbarui1.setForeground(new java.awt.Color(255, 255, 255));
        perbarui1.setText("Perbarui Laporan");
        perbarui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perbarui1ActionPerformed(evt);
            }
        });
        getContentPane().add(perbarui1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 230, 60));

        cari1.setBackground(new java.awt.Color(0, 204, 204));
        cari1.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        cari1.setForeground(new java.awt.Color(255, 255, 255));
        cari1.setText("Cari Laporan");
        cari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1ActionPerformed(evt);
            }
        });
        getContentPane().add(cari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 230, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mnumsy.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here           // Tombol Back -> kembali ke halaman Login
        
    new LOGIN().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
                                       
        if (currentUser != null) {
            new JenisLaporan_U_1(currentUser).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
            new LOGIN().setVisible(true);
        }
        this.dispose();
           

    }//GEN-LAST:event_hapus1ActionPerformed

    private void buat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buat1ActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            new BUATLAPORANLOKASILAUT_1(currentUser).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
            new LOGIN().setVisible(true);
        }
        this.dispose();
        

    }//GEN-LAST:event_buat1ActionPerformed

    private void lihat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihat1ActionPerformed
        // TODO add your handling code here:
            // Tombol Lihat Laporan
    if (currentUser != null) {
        // Buka GUI JenisLaporan untuk melihat laporan
        new JenisLaporan_U_2_1_1(currentUser).setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, 
            "User belum login!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        new LOGIN().setVisible(true);
    }
    this.dispose();
    }//GEN-LAST:event_lihat1ActionPerformed

    private void perbarui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perbarui1ActionPerformed
        // TODO add your handling code here:
            // Tombol Perbarui Laporan
    if (currentUser != null) {
        new JenisLaporan_U_2_1(currentUser).setVisible(true);
    } else {
        JOptionPane.showMessageDialog(this, "User belum login!", "Error", JOptionPane.ERROR_MESSAGE);
        new LOGIN().setVisible(true);
    }
    this.dispose();
    }//GEN-LAST:event_perbarui1ActionPerformed

    private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
        // Buka GUI PilihMenu, kirim user login agar tetap terdeteksi
        new JenisLaporan_U_2_1_1_1(currentUser).setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this,
            "User belum login! Silakan login terlebih dahulu.",
            "Error", JOptionPane.ERROR_MESSAGE);
        new LOGIN().setVisible(true);
        this.dispose();
    }
        
      
    }//GEN-LAST:event_cari1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Menu_Masyarakat().setVisible(true));
    }

        /* Create and display the form */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton buat1;
    private javax.swing.JButton cari1;
    private javax.swing.JButton hapus1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lihat1;
    private javax.swing.JButton perbarui1;
    // End of variables declaration//GEN-END:variables
}
