/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import model.User;
import service.DatabaseConnection;
/**
 *
 * @author asus GK
 */
public class Perbaruilaporanpencemaran_1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Perbaruilaporanpencemaran_1.class.getName());

    private User currentUser;
    private int idLaporan;
    private Connection conn;

    public Perbaruilaporanpencemaran_1(User user, int idLaporan) {
        this.currentUser = user;
        this.idLaporan = idLaporan;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
        loadLaporanData();
    }

    public Perbaruilaporanpencemaran_1() {
        initComponents();
        this.conn = DatabaseConnection.getConnection();
    }

    private void loadLaporanData() {
        try {
            String sql = """
                SELECT l.deskripsi, p.sumber_limbah, p.jenis_limbah, p.tingkat_pencemaran
                FROM laporan l
                JOIN laporan_pencemaran p ON l.id_laporan = p.id_laporan
                WHERE l.id_laporan = ?
            """;

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idLaporan);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                jTextField7.setText(String.valueOf(idLaporan)); // ID laporan
                jTextField7.setEditable(false); // 🔒 tidak bisa diedit
                jTextField6.setText(rs.getString("sumber_limbah"));
                jTextField5.setText(rs.getString("jenis_limbah"));

                String tingkat = rs.getString("tingkat_pencemaran");
                jCheckBox5.setSelected("Ringan".equalsIgnoreCase(tingkat));
                jCheckBox2.setSelected("Sedang".equalsIgnoreCase(tingkat));
                jCheckBox4.setSelected("Berat".equalsIgnoreCase(tingkat));
            } else {
                JOptionPane.showMessageDialog(this, "Data laporan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal load data laporan", e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login4 = new javax.swing.JButton();
        Login3 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login4.setBackground(new java.awt.Color(0, 51, 153));
        Login4.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Login4.setForeground(new java.awt.Color(255, 255, 255));
        Login4.setText("Back");
        Login4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login4ActionPerformed(evt);
            }
        });
        getContentPane().add(Login4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 200, 50));

        Login3.setBackground(new java.awt.Color(0, 51, 153));
        Login3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        Login3.setForeground(new java.awt.Color(255, 255, 255));
        Login3.setText("Send");
        Login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login3ActionPerformed(evt);
            }
        });
        getContentPane().add(Login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 200, 50));

        jCheckBox5.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setText("Ringan");
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 100, 30));

        jCheckBox2.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setText("Sedang");
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 360, 110, 30));

        jCheckBox4.setFont(new java.awt.Font("STHupo", 0, 24)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setText("Berat");
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 360, 100, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 450, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 440, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 450, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Perbaruilaporanpencemaran_1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login4ActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Login4ActionPerformed

    private void Login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login3ActionPerformed
        // TODO add your handling code here:
        String sumber = jTextField6.getText().trim();
        String jenis = jTextField5.getText().trim();
        String tingkat = jCheckBox5.isSelected() ? "Ringan" :
                          jCheckBox2.isSelected() ? "Sedang" :
                          jCheckBox4.isSelected() ? "Berat" : null;

        if (sumber.isEmpty() || jenis.isEmpty() || tingkat == null) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // update tabel laporan
            String sql1 = "UPDATE laporan SET deskripsi=?, status_laporan='Menunggu' WHERE id_laporan=?";
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            ps1.setString(1, "Laporan pencemaran diperbarui oleh masyarakat");
            ps1.setInt(2, idLaporan);
            ps1.executeUpdate();

            // update tabel laporan_pencemaran
            String sql2 = """
                UPDATE laporan_pencemaran
                SET sumber_limbah=?, jenis_limbah=?, tingkat_pencemaran=?
                WHERE id_laporan=?
            """;
            PreparedStatement ps2 = conn.prepareStatement(sql2);
            ps2.setString(1, sumber);
            ps2.setString(2, jenis);
            ps2.setString(3, tingkat);
            ps2.setInt(4, idLaporan);
            ps2.executeUpdate();

            JOptionPane.showMessageDialog(this, "Laporan berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();

        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal update laporan", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    

 
    }//GEN-LAST:event_Login3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Perbaruilaporanpencemaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login3;
    private javax.swing.JButton Login4;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
