/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author asus GK
 */
import java.sql.*;
import javax.swing.*;
import model.User;
import service.DatabaseConnection;

public class Perbaruilaporanpenangkapan_1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Perbaruilaporanpenangkapan_1.class.getName());

    private User currentUser;
    private int idLaporan;
    private Connection conn;

    // Konstruktor utama
    public Perbaruilaporanpenangkapan_1(User user, int idLaporan) {
        this.currentUser = user;
        this.idLaporan = idLaporan;
        this.conn = DatabaseConnection.getConnection();
        initComponents();
        loadLaporanData();
    }

    // Konstruktor default (tidak disarankan)
    public Perbaruilaporanpenangkapan_1() {
        initComponents();
        this.conn = DatabaseConnection.getConnection();
    }

    // 🔹 Fungsi untuk menampilkan data lama berdasarkan id laporan
    private void loadLaporanData() {
        try {
            String sql = """
                SELECT l.deskripsi, p.jenis_kapal, p.alat_tangkap,
                       p.zona_penangkapan, p.pelanggaran
                FROM laporan l
                JOIN laporan_penangkapan_ikan p ON l.id_laporan = p.id_laporan
                WHERE l.id_laporan = ?
                """;

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, idLaporan);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                idlaporan.setText(String.valueOf(idLaporan));
                jeniskapal.setText(rs.getString("jenis_kapal"));
                alattangkap.setText(rs.getString("alat_tangkap"));
                zonapenangkapan.setText(rs.getString("zona_penangkapan"));
                pelanggaran.setText(rs.getString("pelanggaran"));

                // 🔹 Biar ID gak bisa diubah
                idlaporan.setEditable(false);
                idlaporan.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Data laporan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal load data laporan", e);
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskapal = new javax.swing.JTextField();
        alattangkap = new javax.swing.JTextField();
        zonapenangkapan = new javax.swing.JTextField();
        pelanggaran = new javax.swing.JTextField();
        idlaporan = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jeniskapal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeniskapalActionPerformed(evt);
            }
        });
        getContentPane().add(jeniskapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 450, 40));
        getContentPane().add(alattangkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 450, 40));
        getContentPane().add(zonapenangkapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 450, 40));

        pelanggaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelanggaranActionPerformed(evt);
            }
        });
        getContentPane().add(pelanggaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 440, 50));

        idlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idlaporanActionPerformed(evt);
            }
        });
        getContentPane().add(idlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 250, 450, 40));

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 200, 50));

        login.setBackground(new java.awt.Color(0, 51, 153));
        login.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Send");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 200, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Perbaruilaporanpenangkapanikan.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new Menu_Masyarakat(currentUser).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String jenisKapal = jeniskapal.getText().trim();
        String alatTangkap = alattangkap.getText().trim();
        String zona = zonapenangkapan.getText().trim();
        String pel = pelanggaran.getText().trim();

        if (jenisKapal.isEmpty() || alatTangkap.isEmpty() || zona.isEmpty() || pel.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Update tabel laporan (gunakan status valid ENUM)
            String sql1 = "UPDATE laporan SET deskripsi = ?, status_laporan = ? WHERE id_laporan = ?";
            PreparedStatement ps1 = conn.prepareStatement(sql1);
            ps1.setString(1, pel);
            ps1.setString(2, "Ditindak"); // ✅ enum valid: Menunggu / Ditindak / Selesai
            ps1.setInt(3, idLaporan);
            ps1.executeUpdate();

            // Update tabel laporan_penangkapan_ikan
            String sql2 = """
                UPDATE laporan_penangkapan_ikan
                SET jenis_kapal = ?, alat_tangkap = ?, zona_penangkapan = ?, pelanggaran = ?
                WHERE id_laporan = ?
                """;
            PreparedStatement ps2 = conn.prepareStatement(sql2);
            ps2.setString(1, jenisKapal);
            ps2.setString(2, alatTangkap);
            ps2.setString(3, zona);
            ps2.setString(4, pel);
            ps2.setInt(5, idLaporan);
            ps2.executeUpdate();

            JOptionPane.showMessageDialog(this, "✅ Laporan berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            new Menu_Masyarakat(currentUser).setVisible(true);
            this.dispose();
            } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal update laporan", e);
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan DB: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    
    }//GEN-LAST:event_loginActionPerformed

    private void pelanggaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelanggaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelanggaranActionPerformed

    private void idlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idlaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idlaporanActionPerformed

    private void jeniskapalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeniskapalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeniskapalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Perbaruilaporanpenangkapan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alattangkap;
    private javax.swing.JButton back;
    private javax.swing.JTextField idlaporan;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jeniskapal;
    private javax.swing.JButton login;
    private javax.swing.JTextField pelanggaran;
    private javax.swing.JTextField zonapenangkapan;
    // End of variables declaration//GEN-END:variables
}
