/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import model.User;
import javax.swing.*;

/**
 *
 * @author asus GK
 */
public class PilihMenuhapus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(PilihMenuhapus.class.getName());
    
    private User currentUser; // user yang sedang login

    // 🔹 Konstruktor utama — menerima user yang sedang login
    public PilihMenuhapus(User user) {
        this.currentUser = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login7 = new javax.swing.JButton();
        Login6 = new javax.swing.JButton();
        Login5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login7.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        Login7.setForeground(new java.awt.Color(0, 102, 102));
        Login7.setText("back");
        Login7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login7ActionPerformed(evt);
            }
        });
        getContentPane().add(Login7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 110, 40));

        Login6.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        Login6.setForeground(new java.awt.Color(0, 102, 102));
        Login6.setText("Laporan");
        Login6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login6ActionPerformed(evt);
            }
        });
        getContentPane().add(Login6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 190, 60));

        Login5.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        Login5.setForeground(new java.awt.Color(0, 102, 102));
        Login5.setText("Akun");
        Login5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login5ActionPerformed(evt);
            }
        });
        getContentPane().add(Login5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PilihMenu.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1277, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Login6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login6ActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
                new Hapuslaporanadmin(currentUser).setVisible(true);
            // 
            
        } else {
            JOptionPane.showMessageDialog(this, 
                "User belum terdeteksi, harap login terlebih dahulu!", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            new LOGIN().setVisible(true);
            this.dispose();
        }
        
    
    }//GEN-LAST:event_Login6ActionPerformed

    private void Login5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login5ActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
                new Hapusakunanadmin1(currentUser).setVisible(true);
            // 
            
        } else {
            JOptionPane.showMessageDialog(this, 
                "User belum terdeteksi, harap login terlebih dahulu!", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            new LOGIN().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Login5ActionPerformed

    private void Login7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login7ActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            // 
            new Menu_Admin(currentUser).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, 
                "User belum terdeteksi, harap login terlebih dahulu!", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            new LOGIN().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_Login7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login5;
    private javax.swing.JButton Login6;
    private javax.swing.JButton Login7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
