/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import model.User;
import javax.swing.*;


/**
 *
 * @author asus GK
 */
public class PilihMenulihat extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PilihMenulihat.class.getName());
    private User currentUser; // ✅ menyimpan user yang login

    /**
     * Konstruktor default
     */
    public PilihMenulihat(User user) {
        this.currentUser = user;
        initComponents();
    }
    public PilihMenulihat() {
        initComponents();
    }

    /**
     * Konstruktor dengan parameter user (dipanggil dari Menu_Admin)
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        akun = new javax.swing.JButton();
        laporan = new javax.swing.JButton();
        lokasi = new javax.swing.JButton();
        tindak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 102));
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 100, 50));

        akun.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        akun.setForeground(new java.awt.Color(0, 102, 102));
        akun.setText("Akun");
        akun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunActionPerformed(evt);
            }
        });
        getContentPane().add(akun, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 190, 60));

        laporan.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        laporan.setForeground(new java.awt.Color(0, 102, 102));
        laporan.setText("Laporan");
        laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanActionPerformed(evt);
            }
        });
        getContentPane().add(laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 190, 60));

        lokasi.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        lokasi.setForeground(new java.awt.Color(0, 102, 102));
        lokasi.setText("Lokasi Laut");
        lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokasiActionPerformed(evt);
            }
        });
        getContentPane().add(lokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 180, 60));

        tindak.setFont(new java.awt.Font("STHupo", 0, 18)); // NOI18N
        tindak.setForeground(new java.awt.Color(0, 102, 102));
        tindak.setText("Tindak Lanjut");
        tindak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tindakActionPerformed(evt);
            }
        });
        getContentPane().add(tindak, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 420, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pilihmenu4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1277, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void akunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            new Lihatlaporanpencemaran(currentUser).setVisible(true);
            this.dispose();
        } else {
            new Lihatlaporanpencemaran().setVisible(true);
            this.dispose();
        }
    
        
    }//GEN-LAST:event_akunActionPerformed

    private void laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
        new Lihatlaporanpencemaran_22(currentUser).setVisible(true);
    } else {
        new Menu_Admin().setVisible(true);
    }
    this.dispose(); // Tutup halaman sekarang
        
    }//GEN-LAST:event_laporanActionPerformed

    private void lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokasiActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
        new Lihatlaporanlokasi_2_1_1(currentUser).setVisible(true);
    } else {
        new Menu_Admin().setVisible(true);
    }
    this.dispose(); 
        

    }//GEN-LAST:event_lokasiActionPerformed

    private void tindakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tindakActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
        new Lihatlaporanpencemaran_2_1_1(currentUser).setVisible(true);
    } else {
        new Menu_Admin().setVisible(true);
    }
    this.dispose(); // Tutup halaman sekarang
    }//GEN-LAST:event_tindakActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        if (currentUser != null) {
            new Menu_Admin(currentUser).setVisible(true);
        } else {
            new Menu_Admin().setVisible(true); // fallback
        }
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PilihMenulihat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akun;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton laporan;
    private javax.swing.JButton lokasi;
    private javax.swing.JButton tindak;
    // End of variables declaration//GEN-END:variables
}
