/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import javax.swing.*;
import java.awt.event.*;
import model.User;
import service.UserService;
import model.Masyarakat;
import service.UserService;

/**
 *
 * @author asus GK
 */
public class Signin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signin.class.getName());
    private UserService userService = new UserService();

    /**
     * Creates new form WELCOME
     */
    public Signin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Nama_user = new javax.swing.JTextField();
        Sign_in = new javax.swing.JButton();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setBackground(new java.awt.Color(0, 51, 153));
        Back.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(255, 255, 255));
        Back.setText("back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 490, 100, 30));

        Nama_user.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        getContentPane().add(Nama_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 380, 40));

        Sign_in.setBackground(new java.awt.Color(0, 51, 153));
        Sign_in.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        Sign_in.setForeground(new java.awt.Color(255, 255, 255));
        Sign_in.setText("Sign in");
        Sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_inActionPerformed(evt);
            }
        });
        getContentPane().add(Sign_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, 100, 30));

        Email.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 380, 50));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 410, 360, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sign in.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
    new WELCOME().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Sign_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_inActionPerformed
        // TODO add your handling code here:
        String nama = Nama_user.getText().trim();
        String email = Email.getText().trim();
        String password = new String(Password.getPassword()).trim();

        if (nama.isEmpty() || email.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // === Buat objek Masyarakat ===
        Masyarakat m = new Masyarakat() {
            @Override
            public int getId_user() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };
        m.setNamaUser(nama);
        m.setEmail(email);
        m.setPassword(password);
        m.setNoHp("0"); // sementara, bisa ubah di GUI kalau ditambah field
        m.setPeran("Masyarakat");
        m.setNik("NIK" + System.currentTimeMillis()); // dummy unik sementara

        // === Simpan ke DB ===
        boolean sukses = userService.registerMasyarakat(m);

        if (sukses) {
            JOptionPane.showMessageDialog(this, "Registrasi berhasil!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            new LOGIN().setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Registrasi gagal disimpan ke database!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
     

    }//GEN-LAST:event_Sign_inActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new Signin().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Nama_user;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Sign_in;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
